services:
  qdrant:
    image: qdrant/qdrant
    container_name: ${QDRANT_HOST}
    ports:
      - "${QDRANT_PORT}:6333"
      - "6334:6334"
    env_file:
      - .env.compose
    volumes:
      - ${QDRANT_VOL_HOST}:/qdrant/storage

  dataset-service:
    build:
      context: .
      dockerfile: src/services/database/Dockerfile
    profiles: ["on-demand"]
    env_file:
      - .env.compose
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ${CODE_ROOT_HOST}:${CODE_ROOT}
      - ${PROJECT_ROOT_HOST}:${PROJECT_ROOT}
      - ${TEMP_ROOT_HOST}:${TEMP_FOLDER_ROOT}/tmp
      - ${KAGGLE_VOL_HOST}:/root/.kaggle:ro
    depends_on:
      - qdrant


# to start qdrant:
# docker-compose --env-file .env.compose up
#
# to start update service:
# docker-compose --profile on-demand --env-file .env.compose up
# or
# docker-compose run -rm dataset-service update --years 2024 2025