[project]
name = "asxai"
version = "0.1.0"
description = "a RAG pipeline to keep track of scientific articles"
authors = [{ name = "", email = "@" }]
dependencies = []

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"