global:
  scrape_interval: 30s
  evaluation_interval: 30s

scrape_configs:
  - job_name: "chat_api"
    static_configs:
      - targets: ["chat-api:8000"]
  - job_name: "search_api"
    static_configs:
      - targets: ["search-api:8000"]